---
abstract: 'Math::Factoring - Advanced Factoring Algorithms'
author:
  - "Jonathan \"Duke\" Leto <jonathan@leto.net>"
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Factoring
requires:
  Data::Dumper: 0
  Exporter: 0
  Math::GMPz: 0
  Math::Primality: 0
  base: 0
  constant: 0
  strict: 0
  warnings: 0
resources:
  homepage: http://github.com/leto/Math-Factoring
  repository: http://github.com/leto/Math-Factoring.git
version: 0.02
